#! /bin/bash
echo "My chipseq pipeline" 
echo "I like coding"

#! /bin/bash

##Parámetros de entrada
PARAMS=$1
WD=$2
MAIN_FOLDER=$3
GEN=$4
ANNO=$5
INS=$6
CHIPLOC=$7
INPUTLOC=$8

##Lectura de parámetros
WD=$(grep working_directory: $PARAMS | awk '{ print $2}')
echo $WD
MAIN_FOLDER=$(grep main_folder: $PARAMS | awk '{print $2}')
echo $MAIN_FOLDER
GEN=$(grep genome_folder: $PARAMS | awk '{print $2}')
echo $GEN
ANNO=$(grep annotation_folder: $PARAMS | awk '{print $2}')
echo $ANNO
INS=$(grep installation_folder: $PARAMS | awk '{print $2}')
echo "installation_folder:"
echo $INS
CHIPLOC=$(grep chip_location: $PARAMS | awk '{print $2}')
echo $CHIPLOC
INPUTLOC=$(grep input_location: $PARAMS | awk '{print $2}')
echo $INPUTLOC

##Construccion working directory

cd $WD

##create main folder

mkdir ${MAIN_FOLDER}
cd ${MAIN_FOLDER}


## Create subfolders
mkdir genome annotation results samples

##Create chip e input
cd samples
mkdir chip input
cd ../genome
cp $GEN genome.fa
bowtie-build genome.fa index
cd ../annotation
cp $ANNO annotation.gtf

##Mapeo de lecturas al genoma de referencia
qsub -N chip -o chip $INS/read_mapping.sh $WD/$MAIN_FOLDER/samples/chip $CHIPLOC
qsub -N input -o input $INS/read_mapping.sh $WD/$MAIN_FOLDER/samples/input $INPUTLOC

